### ISSUE TITLE
Changes to Habits don't sync between pages/habit tracker page

### ISSUE THREAD

**Issue by TMJSMC53** [TMJSMC53/holistic-health-app#39]
# Recreation of the Problem
 
- Go to Habits page
- Record an enactment
- Visit the History of that Habit
- See that the enactment has not been recorded

- The Current & Max Streak is displaying incorrect values
- The PlusOne button is not showing
- The Last recorded msg is inaccurate

# Potential Solution

## Frontend
In the `Habit.tsx` file: 
- [x] Verify state is used in the correct place for the following: 
  - [x] Current & Max Streak
  - [x] PlusOne button
  - [x] Last seen

### Model
- [x] N/A

### Route
- [x] N/A

### Controller
- [x] N/A

# Acceptence Criteria
- [x] When user clicks on the 'View History' link in the `Habits.tsx' page, the Current Streak & Max Streak display the correct values for both
- [x] The PlusOne button and Last recorded are correct
- [x] We shouldn't have to refresh the page to get that information 
   - [x] It's there automatically
